# Site settings
title: Caitlin Weber
email: caitlin@caitlinweber.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to the portfolio of Caitlin Weber
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://caitlinweber.com" # the base hostname & protocol for your site
twitter_username: caitlinweber
github_username:  cweber
dribbble_username:  cweber
linkedin_username:  cweber

# Build settings
markdown: kramdown



port: 5000


